version: "2.3"
services:
  pts_client:
    container_name: pts_client
    build:
      context: ./client
      dockerfile:
        Dockerfile
    environment:
      REACT_APP_BASE_REQUEST_URL: http://localhost:8080 
      REACT_APP_DOMAIN: localhost
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app    
  pts_api:
    container_name: pts_api
    build:
     context: ./api
     dockerfile:
       Dockerfile
    depends_on:
      - mongodb
    environment:
      REACT_APP_BASE_REQUEST_URL: localhost:8080 
    links:
      - mongodb
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
  mongodb:
    container_name: mongodb
    image: mongo:4.2
    volumes:
            - '/data/db:/data/db:rw'
    expose:
      - "27017"
